elastic-query-service:
  version: v1

server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

user-config:
  username: test
  password: '{cipher}61b311c42187b68c7cf78ffa50262807069fe8bcdc8ea45497a643eed6203f1d'
  roles: USER