elastic-query-service:
  version: v1
  custom-audience: elastic-query-service

server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/microservices-realm
          jwt-set-uri: http://localhost:8081/auth/realms/microservices-realm/protocol/openid-connect/certs

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

user-config:
  username: test
  password: '{cipher}61b311c42187b68c7cf78ffa50262807069fe8bcdc8ea45497a643eed6203f1d'
  roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /api-docs